/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Huseyin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    //
    StopWatch zaman = new StopWatch();
    int hours, minutes, seconds, tempTime = 0;
    //
    boolean puzzleIsTrue = false;

    Color kapali = new Color(65, 218, 255);
    Font font1 = new Font("SansSerif", Font.BOLD, 30);
    GridLayout grid = new GridLayout(9, 9);
    JTextField[][] oyunAlani = new JTextField[9][9];
    Dimension boyut = new Dimension(50, 50);

    int[][] puzzle
            = {{3, 7, 4, 1, 6, 8, 2, 5, 9},
            {5, 1, 9, 4, 2, 7, 6, 8, 3},
            {2, 8, 6, 3, 9, 5, 7, 1, 4},
            {6, 9, 8, 5, 4, 1, 3, 7, 2},
            {1, 2, 3, 7, 8, 6, 9, 4, 5},
            {4, 5, 7, 9, 3, 2, 1, 6, 8},
            {9, 6, 2, 8, 7, 4, 5, 3, 1},
            {8, 3, 5, 6, 1, 9, 4, 2, 7},
            {7, 4, 1, 2, 5, 3, 8, 9, 6}};
    boolean[][] masks
            = {{false, true, false, false, false, false, false, false, true},
            {true, true, false, true, true, false, true, false, false},
            {false, true, false, true, false, false, true, false, false},
            {false, false, true, false, false, true, true, true, false},
            {false, true, true, false, true, false, false, true, false},
            {true, false, false, true, false, false, true, false, false},
            {true, true, true, true, false, false, false, true, false},
            {false, false, false, false, true, false, true, false, false},
            {true, false, false, true, false, true, false, true, true}};

    private void gridEkle() {
        jPanel1.setLayout(grid);
        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                oyunAlani[i][j] = new JTextField();
                oyunAlani[i][j].setText(null);
                jPanel1.add(oyunAlani[i][j]);
                oyunAlani[i][j].setPreferredSize(boyut);
                oyunAlani[i][j].setFont(font1);
                oyunAlani[i][j].setHorizontalAlignment(JTextField.CENTER);
                oyunAlani[i][j].setEditable(true);
                if (masks[i][j]) {
                    oyunAlani[i][j].setEditable(false);
                    oyunAlani[i][j].setBackground(kapali);
                    oyunAlani[i][j].setText(Integer.toString(puzzle[i][j]));

                }

            }
        }
    }

    public NewJFrame() {
        setTitle("Sudoku");
        initComponents();
        gridEkle();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jButton1.setText("KONTROL ET");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sudokuKontrolEt() {
        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {

                if (oyunAlani[i][j].getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Hata boş kutular var! 20 saniye ceza eklendi.");
                    return;
                } else if (Integer.parseInt(oyunAlani[i][j].getText()) != puzzle[i][j]) {
                    JOptionPane.showMessageDialog(null, "Hatalı! 20 saniye ceza eklendi.");
                    return;
                } else if (i == 8 && j == 8) {
                    puzzleIsTrue = true;
                }
            }

        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sudokuKontrolEt();
        if (puzzleIsTrue) {
            zaman.stop();
            seconds = (int) zaman.getElapsedTimeSecs();
            seconds += tempTime;
            minutes = seconds / 60;
            hours = minutes / 60;
            seconds %= 60;
            minutes %= 60;
            hours %= 24;
            JOptionPane.showMessageDialog(null, "Süreniz: " + hours + ":" + minutes + ":" + seconds);
            puzzleIsTrue=false;
        } else {
            tempTime += 20;   
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
